### ISSUE TITLE
"Resource not found" error when loading with turtlebot3

### ISSUE THREAD

**Issue by erinline** [aws-robotics/aws-robomaker-small-house-world#4] opened 2019-07-03 15:45 UTC
When I run any of the turtlebot commands, e.g. 
`roslaunch aws_robomaker_small_house_world small_house_turtlebot_navigation.launch gui:=true`
I get the error:
`Resource not found: turtlebot3_description_reduced_mesh`

I have no trouble loading the world itself though, if for example I run
`roslaunch aws_robomaker_small_house_world view_small_house.launch`

Where can I find this missing file?

In case it's relevant, I am running ROS Melodic on Ubuntu 18.04.

**Comment by xabxx** [comment] 2019-07-08 18:20
@erinline Hi there. Could you provide me with steps to reproduce this? Thanks!

**Comment by mm318** [comment] 2019-07-17 22:44
Hi @erinline, this repo was intended to be an assets library. Sorry that it wasn't sufficiently prepared to do everything outlined in the README.

If you would like to run `roslaunch aws_robomaker_small_house_world small_house_turtlebot_navigation.launch gui:=true`, you can do the following before running `rosdep install` and `colcon build`:
1. Download [this file](https://raw.githubusercontent.com/aws-robotics/aws-robomaker-sample-application-persondetection/master/simulation_ws/src/turtlebot3_description_reduced_mesh/launch/spawn_turtlebot.launch) to `aws-robomaker-small-house-world/launch`
2. In the file you just downloaded, replace `turtlebot3_description_reduced_mesh` with `turtlebot3_description`
3. In `aws-robomaker-small-house-world/launch/small_house_turtlebot_navigation.launch`, replace `turtlebot3_description_reduced_mesh` with `aws_robomaker_small_house_world`

Also, please note that the Turtlebot is better supported on ROS Kinetic. Sorry for the inconvenience.

**Comment by AAlon** [comment] 2019-08-09 03:20
Closing this, feel free to open another issue if you're still having issues with the small house world.

**Closed as completed by AAlon** 2019-08-09 03:20 UTC
